name: bodt_chat
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.6
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.7.3
  firebase_auth: ^0.5.12
  google_sign_in: ^3.0.4
  firebase_database: ^1.0.2
  flutter_colorpicker: any

  dynamic_theme:
    git:
      url: git://github.com/Norbert515/dynamic_theme.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.6.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
#  image_path_android: "assets/icon/ic_launcher_android.png"
#  image_path_ios: "assets/icon/ic_launcher_ios.png"
#  adaptive_icon_background: "#FFFAFAFA"
#  adaptive_icon_foreground: "assets/icon/icon-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/flags/
  fonts:
    - family: solid
      fonts:
        - asset: assets/fonts/fontawesome/otfs/solid-900.otf
    - family: curvy
      fonts:
        - asset: assets/fonts/AguafinaScript-Regular.ttf