import 'package:bodt_chat/dataUtils/dataBundles.dart';

class CountryList {
  static List<CountryData> countries = [
    CountryData(name: "Andorra", isoCode: "AD", phoneCode: "+376"),
    CountryData(name: "United Arab Emirates", isoCode: "AE", phoneCode: "+971"),
    CountryData(name: "Afghanistan", isoCode: "AF", phoneCode: "+93"),
    CountryData(name: "Antigua and Barbuda", isoCode: "AG", phoneCode: "+1"),
    CountryData(name: "Anguilla", isoCode: "AI", phoneCode: "+1"),
    CountryData(name: "Albania", isoCode: "AL", phoneCode: "+355"),
    CountryData(name: "Armenia", isoCode: "AM", phoneCode: "+374"),
    CountryData(name: "Angola", isoCode: "AO", phoneCode: "+244"),
    CountryData(name: "Antarctica", isoCode: "AQ", phoneCode: "+672"),
    CountryData(name: "Argentina", isoCode: "AR", phoneCode: "+54"),
    CountryData(name: "American Samoa", isoCode: "AS", phoneCode: "+1"),
    CountryData(name: "Austria", isoCode: "AT", phoneCode: "+43"),
    CountryData(name: "Australia", isoCode: "AU", phoneCode: "+61"),
    CountryData(name: "Aruba", isoCode: "AW", phoneCode: "+297"),
    CountryData(name: "Aland Islands", isoCode: "AX", phoneCode: "+358"),
    CountryData(name: "Azerbaijan", isoCode: "AZ", phoneCode: "+994"),
    CountryData(name: "Bosnia and Herzegovina", isoCode: "BA", phoneCode: "+387"),
    CountryData(name: "Barbados", isoCode: "BB", phoneCode: "+1"),
    CountryData(name: "Bangladesh", isoCode: "BD", phoneCode: "+880"),
    CountryData(name: "Belgium", isoCode: "BE", phoneCode: "+32"),
    CountryData(name: "Burkina Faso", isoCode: "BF", phoneCode: "+226"),
    CountryData(name: "Bulgaria", isoCode: "BG", phoneCode: "+359"),
    CountryData(name: "Bahrain", isoCode: "BH", phoneCode: "+973"),
    CountryData(name: "Burundi", isoCode: "BI", phoneCode: "+257"),
    CountryData(name: "Benin", isoCode: "BJ", phoneCode: "+229"),
    CountryData(name: "Saint Barthelemy", isoCode: "BL", phoneCode: "+590"),
    CountryData(name: "Bermuda", isoCode: "BM", phoneCode: "+1"),
    CountryData(name: "Brunei Darussalam", isoCode: "BN", phoneCode: "+673"),
    CountryData(name: "Bolivia, Plurinational State of", isoCode: "BO", phoneCode: "+591"),
    CountryData(name: "Bonaire", isoCode: "BQ", phoneCode: "+599"),
    CountryData(name: "Brazil", isoCode: "BR", phoneCode: "+55"),
    CountryData(name: "Bahamas", isoCode: "BS", phoneCode: "+1"),
    CountryData(name: "Bhutan", isoCode: "BT", phoneCode: "+975"),
    CountryData(name: "Bouvet Island", isoCode: "BV", phoneCode: "+47"),
    CountryData(name: "Botswana", isoCode: "BW", phoneCode: "+267"),
    CountryData(name: "Belarus", isoCode: "BY", phoneCode: "+375"),
    CountryData(name: "Belize", isoCode: "BZ", phoneCode: "+501"),
    CountryData(name: "Canada", isoCode: "CA", phoneCode: "+1"),
    CountryData(name: "Cocos (Keeling) Islands", isoCode: "CC", phoneCode: "+61"),
    CountryData(name: "Congo, The Democratic Republic of the", isoCode: "CD", phoneCode: "+243"),
    CountryData(name: "Central African Republic", isoCode: "CF", phoneCode: "+236"),
    CountryData(name: "Congo", isoCode: "CG", phoneCode: "+242"),
    CountryData(name: "Switzerland", isoCode: "CH", phoneCode: "+41"),
    CountryData(name: "Ivory Coast", isoCode: "CI", phoneCode: "+225"),
    CountryData(name: "Cook Islands", isoCode: "CK", phoneCode: "+682"),
    CountryData(name: "Chile", isoCode: "CL", phoneCode: "+56"),
    CountryData(name: "Cameroon", isoCode: "CM", phoneCode: "+237"),
    CountryData(name: "China", isoCode: "CN", phoneCode: "+86"),
    CountryData(name: "Colombia", isoCode: "CO", phoneCode: "+57"),
    CountryData(name: "Costa Rica", isoCode: "CR", phoneCode: "+506"),
    CountryData(name: "Cuba", isoCode: "CU", phoneCode: "+53"),
    CountryData(name: "Cape Verde", isoCode: "CV", phoneCode: "+238"),
    CountryData(name: "Curacao", isoCode: "CW", phoneCode: "+599"),
    CountryData(name: "Christmas Island", isoCode: "CX", phoneCode: "+61"),
    CountryData(name: "Cyprus", isoCode: "CY", phoneCode: "+357"),
    CountryData(name: "Czech Republic", isoCode: "CZ", phoneCode: "+420"),
    CountryData(name: "Germany", isoCode: "DE", phoneCode: "+49"),
    CountryData(name: "Djibouti", isoCode: "DJ", phoneCode: "+253"),
    CountryData(name: "Denmark", isoCode: "DK", phoneCode: "+45"),
    CountryData(name: "Dominica", isoCode: "DM", phoneCode: "+1"),
    CountryData(name: "Dominican Republic", isoCode: "DO", phoneCode: "+1"),
    CountryData(name: "Algeria", isoCode: "DZ", phoneCode: "+213"),
    CountryData(name: "Ecuador", isoCode: "EC", phoneCode: "+593"),
    CountryData(name: "Estonia", isoCode: "EE", phoneCode: "+372"),
    CountryData(name: "Egypt", isoCode: "EG", phoneCode: "+20"),
    CountryData(name: "Western Sahara", isoCode: "EH", phoneCode: "+212"),
    CountryData(name: "Eritrea", isoCode: "ER", phoneCode: "+291"),
    CountryData(name: "Spain", isoCode: "ES", phoneCode: "+34"),
    CountryData(name: "Ethiopia", isoCode: "ET", phoneCode: "+251"),
    CountryData(name: "Finland", isoCode: "FI", phoneCode: "+358"),
    CountryData(name: "Fiji", isoCode: "FJ", phoneCode: "+679"),
    CountryData(name: "Falkland Islands (Malvinas)", isoCode: "FK", phoneCode: "+500"),
    CountryData(name: "Micronesia, Federated States of", isoCode: "FM", phoneCode: "+691"),
    CountryData(name: "Faroe Islands", isoCode: "FO", phoneCode: "+298"),
    CountryData(name: "France", isoCode: "FR", phoneCode: "+33"),
    CountryData(name: "Gabon", isoCode: "GA", phoneCode: "+241"),
    CountryData(name: "United Kingdom", isoCode: "GB", phoneCode: "+44"),
    CountryData(name: "Grenada", isoCode: "GD", phoneCode: "+1"),
    CountryData(name: "Georgia", isoCode: "GE", phoneCode: "+995"),
    CountryData(name: "French Guiana", isoCode: "GF", phoneCode: "+594"),
    CountryData(name: "Guernsey", isoCode: "GG", phoneCode: "+44"),
    CountryData(name: "Ghana", isoCode: "GH", phoneCode: "+233"),
    CountryData(name: "Gibraltar", isoCode: "GI", phoneCode: "+350"),
    CountryData(name: "Greenland", isoCode: "GL", phoneCode: "+299"),
    CountryData(name: "Gambia", isoCode: "GM", phoneCode: "+220"),
    CountryData(name: "Guinea", isoCode: "GN", phoneCode: "+224"),
    CountryData(name: "Guadeloupe", isoCode: "GP", phoneCode: "+590"),
    CountryData(name: "Equatorial Guinea", isoCode: "GQ", phoneCode: "+240"),
    CountryData(name: "Greece", isoCode: "GR", phoneCode: "+30"),
    CountryData(name: "South Georgia and the South Sandwich Islands", isoCode: "GS", phoneCode: "+500"),
    CountryData(name: "Guatemala", isoCode: "GT", phoneCode: "+502"),
    CountryData(name: "Guam", isoCode: "GU", phoneCode: "+1"),
    CountryData(name: "Guinea-Bissau", isoCode: "GW", phoneCode: "+245"),
    CountryData(name: "Guyana", isoCode: "GY", phoneCode: "+595"),
    CountryData(name: "Hong Kong", isoCode: "HK", phoneCode: "+852"),
    CountryData(name: "Heard Island and McDonald Islands", isoCode: "HM", phoneCode: "+000"),
    CountryData(name: "Honduras", isoCode: "HN", phoneCode: "+504"),
    CountryData(name: "Croatia", isoCode: "HR", phoneCode: "+385"),
    CountryData(name: "Haiti", isoCode: "HT", phoneCode: "+509"),
    CountryData(name: "Hungary", isoCode: "HU", phoneCode: "+36"),
    CountryData(name: "Indonesia", isoCode: "ID", phoneCode: "+62"),
    CountryData(name: "Ireland", isoCode: "IE", phoneCode: "+353"),
    CountryData(name: "Israel", isoCode: "IL", phoneCode: "+972"),
    CountryData(name: "Isle of Man", isoCode: "IM", phoneCode: "+44"),
    CountryData(name: "India", isoCode: "IN", phoneCode: "+91"),
    CountryData(name: "British Indian Ocean Territory", isoCode: "IO", phoneCode: "+246"),
    CountryData(name: "Iraq", isoCode: "IQ", phoneCode: "+964"),
    CountryData(name: "Iran, Islamic Republic of", isoCode: "IR", phoneCode: "+98"),
    CountryData(name: "Iceland", isoCode: "IS", phoneCode: "+354"),
    CountryData(name: "Italy", isoCode: "IT", phoneCode: "+39"),
    CountryData(name: "Jersey", isoCode: "JE", phoneCode: "+44"),
    CountryData(name: "Jamaica", isoCode: "JM", phoneCode: "+1"),
    CountryData(name: "Jordan", isoCode: "JO", phoneCode: "+962"),
    CountryData(name: "Japan", isoCode: "JP", phoneCode: "+81"),
    CountryData(name: "Kenya", isoCode: "KE", phoneCode: "+254"),
    CountryData(name: "Kyrgyzstan", isoCode: "KG", phoneCode: "+996"),
    CountryData(name: "Cambodia", isoCode: "KH", phoneCode: "+855"),
    CountryData(name: "Kiribati", isoCode: "KI", phoneCode: "+686"),
    CountryData(name: "Comoros", isoCode: "KM", phoneCode: "+269"),
    CountryData(name: "Saint Kitts and Nevis", isoCode: "KN", phoneCode: "+1"),
    CountryData(name: "North Korea", isoCode: "KP", phoneCode: "+850"),
    CountryData(name: "South Korea", isoCode: "KR", phoneCode: "+82"),
    CountryData(name: "Kuwait", isoCode: "KW", phoneCode: "+965"),
    CountryData(name: "Cayman Islands", isoCode: "KY", phoneCode: "+345"),
    CountryData(name: "Kazakhstan", isoCode: "KZ", phoneCode: "+7"),
    CountryData(name: "Lao People's Democratic Republic", isoCode: "LA", phoneCode: "+856"),
    CountryData(name: "Lebanon", isoCode: "LB", phoneCode: "+961"),
    CountryData(name: "Saint Lucia", isoCode: "LC", phoneCode: "+1"),
    CountryData(name: "Liechtenstein", isoCode: "LI", phoneCode: "+423"),
    CountryData(name: "Sri Lanka", isoCode: "LK", phoneCode: "+94"),
    CountryData(name: "Liberia", isoCode: "LR", phoneCode: "+231"),
    CountryData(name: "Lesotho", isoCode: "LS", phoneCode: "+266"),
    CountryData(name: "Lithuania", isoCode: "LT", phoneCode: "+370"),
    CountryData(name: "Luxembourg", isoCode: "LU", phoneCode: "+352"),
    CountryData(name: "Latvia", isoCode: "LV", phoneCode: "+371"),
    CountryData(name: "Libyan Arab Jamahiriya", isoCode: "LY", phoneCode: "+218"),
    CountryData(name: "Morocco", isoCode: "MA", phoneCode: "+212"),
    CountryData(name: "Monaco", isoCode: "MC", phoneCode: "+377"),
    CountryData(name: "Moldova, Republic of", isoCode: "MD", phoneCode: "+373"),
    CountryData(name: "Montenegro", isoCode: "ME", phoneCode: "+382"),
    CountryData(name: "Saint Martin", isoCode: "MF", phoneCode: "+590"),
    CountryData(name: "Madagascar", isoCode: "MG", phoneCode: "+261"),
    CountryData(name: "Marshall Islands", isoCode: "MH", phoneCode: "+692"),
    CountryData(name: "Macedonia, The Former Yugoslav Republic of", isoCode: "MK", phoneCode: "+389"),
    CountryData(name: "Mali", isoCode: "ML", phoneCode: "+223"),
    CountryData(name: "Myanmar", isoCode: "MM", phoneCode: "+95"),
    CountryData(name: "Mongolia", isoCode: "MN", phoneCode: "+976"),
    CountryData(name: "Macao", isoCode: "MO", phoneCode: "+853"),
    CountryData(name: "Northern Mariana Islands", isoCode: "MP", phoneCode: "+1"),
    CountryData(name: "Martinique", isoCode: "MQ", phoneCode: "+596"),
    CountryData(name: "Mauritania", isoCode: "MR", phoneCode: "+222"),
    CountryData(name: "Montserrat", isoCode: "MS", phoneCode: "+1"),
    CountryData(name: "Malta", isoCode: "MT", phoneCode: "+356"),
    CountryData(name: "Mauritius", isoCode: "MU", phoneCode: "+230"),
    CountryData(name: "Maldives", isoCode: "MV", phoneCode: "+960"),
    CountryData(name: "Malawi", isoCode: "MW", phoneCode: "+265"),
    CountryData(name: "Mexico", isoCode: "MX", phoneCode: "+52"),
    CountryData(name: "Malaysia", isoCode: "MY", phoneCode: "+60"),
    CountryData(name: "Mozambique", isoCode: "MZ", phoneCode: "+258"),
    CountryData(name: "Namibia", isoCode: "NA", phoneCode: "+264"),
    CountryData(name: "New Caledonia", isoCode: "NC", phoneCode: "+687"),
    CountryData(name: "Niger", isoCode: "NE", phoneCode: "+227"),
    CountryData(name: "Norfolk Island", isoCode: "NF", phoneCode: "+672"),
    CountryData(name: "Nigeria", isoCode: "NG", phoneCode: "+234"),
    CountryData(name: "Nicaragua", isoCode: "NI", phoneCode: "+505"),
    CountryData(name: "Netherlands", isoCode: "NL", phoneCode: "+31"),
    CountryData(name: "Norway", isoCode: "NO", phoneCode: "+47"),
    CountryData(name: "Nepal", isoCode: "NP", phoneCode: "+977"),
    CountryData(name: "Nauru", isoCode: "NR", phoneCode: "+674"),
    CountryData(name: "Niue", isoCode: "NU", phoneCode: "+683"),
    CountryData(name: "New Zealand", isoCode: "NZ", phoneCode: "+64"),
    CountryData(name: "Oman", isoCode: "OM", phoneCode: "+968"),
    CountryData(name: "Panama", isoCode: "PA", phoneCode: "+507"),
    CountryData(name: "Peru", isoCode: "PE", phoneCode: "+51"),
    CountryData(name: "French Polynesia", isoCode: "PF", phoneCode: "+689"),
    CountryData(name: "Papua New Guinea", isoCode: "PG", phoneCode: "+675"),
    CountryData(name: "Philippines", isoCode: "PH", phoneCode: "+63"),
    CountryData(name: "Pakistan", isoCode: "PK", phoneCode: "+92"),
    CountryData(name: "Poland", isoCode: "PL", phoneCode: "+48"),
    CountryData(name: "Saint Pierre and Miquelon", isoCode: "PM", phoneCode: "+508"),
    CountryData(name: "Pitcairn", isoCode: "PN", phoneCode: "+872"),
    CountryData(name: "Puerto Rico", isoCode: "PR", phoneCode: "+1"),
    CountryData(name: "Palestinian Territory, Occupied", isoCode: "PS", phoneCode: "+970"),
    CountryData(name: "Portugal", isoCode: "PT", phoneCode: "+351"),
    CountryData(name: "Palau", isoCode: "PW", phoneCode: "+680"),
    CountryData(name: "Paraguay", isoCode: "PY", phoneCode: "+595"),
    CountryData(name: "Qatar", isoCode: "QA", phoneCode: "+974"),
    CountryData(name: "Reunion", isoCode: "RE", phoneCode: "+262"),
    CountryData(name: "Romania", isoCode: "RO", phoneCode: "+40"),
    CountryData(name: "Serbia", isoCode: "RS", phoneCode: "+381"),
    CountryData(name: "Russia", isoCode: "RU", phoneCode: "+7"),
    CountryData(name: "Rwanda", isoCode: "RW", phoneCode: "+250"),
    CountryData(name: "Saudi Arabia", isoCode: "SA", phoneCode: "+966"),
    CountryData(name: "Solomon Islands", isoCode: "SB", phoneCode: "+677"),
    CountryData(name: "Seychelles", isoCode: "SC", phoneCode: "+248"),
    CountryData(name: "Sudan", isoCode: "SD", phoneCode: "+249"),
    CountryData(name: "Sweden", isoCode: "SE", phoneCode: "+46"),
    CountryData(name: "Singapore", isoCode: "SG", phoneCode: "+65"),
    CountryData(name: "Saint Helena, Ascension and Tristan Da Cunha", isoCode: "SH", phoneCode: "+290"),
    CountryData(name: "Slovenia", isoCode: "SI", phoneCode: "+386"),
    CountryData(name: "Svalbard and Jan Mayen", isoCode: "SJ", phoneCode: "+47"),
    CountryData(name: "Slovakia", isoCode: "SK", phoneCode: "+421"),
    CountryData(name: "Sierra Leone", isoCode: "SL", phoneCode: "+232"),
    CountryData(name: "San Marino", isoCode: "SM", phoneCode: "+378"),
    CountryData(name: "Senegal", isoCode: "SN", phoneCode: "+221"),
    CountryData(name: "Somalia", isoCode: "SO", phoneCode: "+252"),
    CountryData(name: "Suriname", isoCode: "SR", phoneCode: "+597"),
    CountryData(name: "South Sudan", isoCode: "SS", phoneCode: "+211"),
    CountryData(name: "Sao Tome and Principe", isoCode: "ST", phoneCode: "+239"),
    CountryData(name: "El Salvador", isoCode: "SV", phoneCode: "+503"),
    CountryData(name: "Sint Maarten", isoCode: "SX", phoneCode: "+1"),
    CountryData(name: "Syrian Arab Republic", isoCode: "SY", phoneCode: "+963"),
    CountryData(name: "Swaziland", isoCode: "SZ", phoneCode: "+268"),
    CountryData(name: "Turks and Caicos Islands", isoCode: "TC", phoneCode: "+1"),
    CountryData(name: "Chad", isoCode: "TD", phoneCode: "+235"),
    CountryData(name: "French Southern Territories", isoCode: "TF", phoneCode: "+262"),
    CountryData(name: "Togo", isoCode: "TG", phoneCode: "+228"),
    CountryData(name: "Thailand", isoCode: "TH", phoneCode: "+66"),
    CountryData(name: "Tajikistan", isoCode: "TJ", phoneCode: "+992"),
    CountryData(name: "Tokelau", isoCode: "TK", phoneCode: "+690"),
    CountryData(name: "East Timor", isoCode: "TL", phoneCode: "+670"),
    CountryData(name: "Turkmenistan", isoCode: "TM", phoneCode: "+993"),
    CountryData(name: "Tunisia", isoCode: "TN", phoneCode: "+216"),
    CountryData(name: "Tonga", isoCode: "TO", phoneCode: "+676"),
    CountryData(name: "Turkey", isoCode: "TR", phoneCode: "+90"),
    CountryData(name: "Trinidad and Tobago", isoCode: "TT", phoneCode: "+1"),
    CountryData(name: "Tuvalu", isoCode: "TV", phoneCode: "+688"),
    CountryData(name: "Taiwan", isoCode: "TW", phoneCode: "+886"),
    CountryData(name: "Tanzania, United Republic of", isoCode: "TZ", phoneCode: "+255"),
    CountryData(name: "Ukraine", isoCode: "UA", phoneCode: "+380"),
    CountryData(name: "Uganda", isoCode: "UG", phoneCode: "+256"),
    CountryData(name: "U.S. Minor Outlying Islands", isoCode: "UM", phoneCode: "+1"),
    CountryData(name: "United States", isoCode: "US", phoneCode: "+1"),
    CountryData(name: "Uruguay", isoCode: "UY", phoneCode: "+598"),
    CountryData(name: "Uzbekistan", isoCode: "UZ", phoneCode: "+998"),
    CountryData(name: "Holy See (Vatican City State)", isoCode: "VA", phoneCode: "+379"),
    CountryData(name: "Saint Vincent and the Grenadines", isoCode: "VC", phoneCode: "+1"),
    CountryData(name: "Venezuela, Bolivarian Republic of", isoCode: "VE", phoneCode: "+58"),
    CountryData(name: "Virgin Islands, British", isoCode: "VG", phoneCode: "+1"),
    CountryData(name: "Virgin Islands, U.S.", isoCode: "VI", phoneCode: "+1"),
    CountryData(name: "Vietnam", isoCode: "VN", phoneCode: "+84"),
    CountryData(name: "Vanuatu", isoCode: "VU", phoneCode: "+678"),
    CountryData(name: "Wallis and Futuna", isoCode: "WF", phoneCode: "+681"),
    CountryData(name: "Samoa", isoCode: "WS", phoneCode: "+685"),
    CountryData(name: "Kosovo", isoCode: "XK", phoneCode: "+383"),
    CountryData(name: "Yemen", isoCode: "YE", phoneCode: "+967"),
    CountryData(name: "Mayotte", isoCode: "YT", phoneCode: "+262"),
    CountryData(name: "South Africa", isoCode: "ZA", phoneCode: "+27"),
    CountryData(name: "Zambia", isoCode: "ZM", phoneCode: "+260"),
    CountryData(name: "Zimbabwe", isoCode: "ZW", phoneCode: "+263")
  ];
}